      - name: Sync Zotero → Readwise (use @citationkey as title)
        env:
          READWISE_TOKEN: ${{ secrets.READWISE_TOKEN }}
          ZOTERO_KEY: ${{ secrets.ZOTERO_KEY }}
          ZOTERO_ID: ${{ secrets.ZOTERO_ID }}
        run: |
          python - <<'PY'
          import os, re
          from zotero2readwise.zt2rw import Zotero2Readwise

          z = Zotero2Readwise(
              readwise_token=os.environ["READWISE_TOKEN"],
              zotero_key=os.environ["ZOTERO_KEY"],
              zotero_library_id=os.environ["ZOTERO_ID"],
              zotero_library_type="user",
              include_annotations=True,
              include_notes=True,
          )

          print("🔧 Custom title rewrite: start")

          # Build the full Zotero item list explicitly
          anns = z.retrieve_all("annotation", z.since)
          notes = z.retrieve_all("note", z.since)
          items = anns + notes
          print(f"   • Retrieved {len(items)} Zotero items")

          # Replace Zotero DATA.title with @citationkey when found in the Extra field
          changed = 0
          for it in items:
              d = it.get("data", {})
              extra = (d.get("extra") or "")
              m = re.search(r"(?i)Citation\s*Key\s*:\s*(\S+)", extra)
              if m:
                  key = m.group(1).strip()
                  if key:
                      d["title"] = f"@{key}"
                      changed += 1

          print(f"   • Titles changed to @citationkey on {changed} items")

          # Format and upload
          print("   • Formatting…")
          formatted = z.formatter.format_items(items)
          print("   • Uploading to Readwise…")
          z.readwise.post_zotero_annotations_to_readwise(formatted)

          print("✅ Done. (@citationkey titles applied where available)")
          PY
