      - name: Run Zotero → Readwise Sync (use Citation Key as title)
        env:
          READWISE_TOKEN: ${{ secrets.READWISE_TOKEN }}
          ZOTERO_KEY: ${{ secrets.ZOTERO_KEY }}
          ZOTERO_ID: ${{ secrets.ZOTERO_ID }}
        run: |
          python - <<'PY'
          import os
          from zotero2readwise.zt2rw import Zotero2Readwise

          z = Zotero2Readwise(
              readwise_token=os.environ["READWISE_TOKEN"],
              zotero_key=os.environ["ZOTERO_KEY"],
              zotero_library_id=os.environ["ZOTERO_ID"],
              zotero_library_type="user",
              include_annotations=True,
              include_notes=True,
          )

          try:
              # Pull Zotero items and replace titles with Better BibTeX Citation Key when available
              items = z.get_all_zotero_items()
              changed = 0
              for it in items:
                  data = it.get("data", {})
                  extra = (data.get("extra") or "")
                  if "Citation Key:" in extra:
                      key = extra.split("Citation Key:", 1)[1].strip().splitlines()[0].strip()
                      if key:
                          data["title"] = key
                          changed += 1

              formatted = z.formatter.format_items(items)
              z.readwise.post_zotero_annotations_to_readwise(formatted)
              print(f"✅ Done. Titles replaced with Citation Key on {changed} items.")
          except Exception as e:
              print(f"⚠️ Fallback to default run due to: {e}")
              z.run()
              print("✅ Done (default titles).")
          PY
