name: Zotero to Readwise Automation

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install zotero2readwise
        run: |
          pip install --upgrade pip
          pip install zotero2readwise

      - name: Sync Zotero -> Readwise (force @citationkey titles; resolve parents)
        env:
          READWISE_TOKEN: ${{ secrets.READWISE_TOKEN }}
          ZOTERO_KEY: ${{ secrets.ZOTERO_KEY }}
          ZOTERO_ID: ${{ secrets.ZOTERO_ID }}
        run: |
          python - <<'PY'
          import os, re
          from zotero2readwise.zt2rw import Zotero2Readwise

          z = Zotero2Readwise(
              readwise_token=os.environ["READWISE_TOKEN"],
              zotero_key=os.environ["ZOTERO_KEY"],
              zotero_library_id=os.environ["ZOTERO_ID"],
              zotero_library_type="user",
              include_annotations=True,
              include_notes=True,
          )

          raw = z.get_all_zotero_items()

          annot_attach_keys = set()
          note_parent_keys = set()
          for it in raw:
              d = it.get("data", {})
              t = d.get("itemType")
              if t == "annotation" and d.get("parentItem"):
                  annot_attach_keys.add(d["parentItem"])
              elif t == "note" and d.get("parentItem"):
                  note_parent_keys.add(d["parentItem"])

          def fetch_items(keys):
              keys = list(keys)
              for i in range(0, len(keys), 50):
                  batch = keys[i:i+50]
                  for itm in z.zotero_client.items(itemKey=",".join(batch)):
                      yield itm

          attach_to_top = {}
          if annot_attach_keys:
              for att in fetch_items(annot_attach_keys):
                  ad = att.get("data", {})
                  if ad.get("itemType") == "attachment" and ad.get("parentItem"):
                      attach_to_top[ad["key"]] = ad["parentItem"]

          top_level_keys = set(note_parent_keys)
          top_level_keys.update(attach_to_top.values())

          rx = re.compile(r"(?im)^citation\s*key\s*[:=]\s*([A-Za-z0-9._:+\-]+)")
          top_to_ck = {}
          if top_level_keys:
              for top in fetch_items(top_level_keys):
                  td = top.get("data", {})
                  ck = td.get("citationKey")
                  if not ck:
                      extra = td.get("extra") or ""
                      m = rx.search(extra)
                      if m:
                          ck = m.group(1).strip()
                  if ck:
                      top_to_ck[td.get("key")] = ck

          print(f"Resolved {len(annot_attach_keys)} attachments to {len(top_level_keys)} top-level items")
          print(f"Collected {len(top_to_ck)} citation keys from top-level items")

          orig_create = z.readwise.create_highlights

          def extract_item_key_from_link(link: str):
              if "zotero://select/items/" not in link:
                  return None
              tail = link.rsplit("/", 1)[-1]
              return tail.split("_")[-1]

          def safe_create(highlights):
              changed = 0
              for h in highlights:
                  link = h.get("source_url") or ""
                  key = extract_item_key_from_link(link)
                  if not key:
                      continue
                  top = attach_to_top.get(key, key)
                  ck = top_to_ck.get(top)
                  if ck:
                      h["title"] = f"@{ck}"
                      changed += 1
              print(f"Rewrote {changed} Readwise titles to @citationkey")
              return orig_create(highlights)

          z.readwise.create_highlights = safe_create

          print("Starting sync…")
          z.run()
          print("Done.")
          PY
